---
log_level: debug-color
introspection_addr: ""
http_listen_addr: ":6000"
updaters: {}
indexer:
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  indexer_addr: http://clair-traefik:6060/
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  max_conn_pool: 100
  migrations: true
matchers:
   # names:
   # - crda
   # config:
   #  crda:
   #    url: https://f8a-analytics-2445582058137.production.gw.apicast.io/?user_key=9e7da76708fe374d8c10fa752e72989f
   #    source: "trial"
   #    key: "trial"
notifier:
  indexer_addr: http://clair-traefik:6060/
  matcher_addr: http://clair-traefik:6060/
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  migrations: true
  delivery_interval: 5s
  poll_interval: 15s
  # webhook:
  #   target: "http://webhook/"
  #   callback: "http://clair-notifier/notifier/api/v1/notifications"
  amqp:
    direct: true
    exchange:
      name: ""
      type: "direct"
      durable: true
      auto_delete: false
    uris: ["amqp://guest:guest@clair-rabbitmq:5672/"]
    routing_key: "notifications"
    callback: "http://clair-notifier/notifier/api/v1/notifications"
# tracing and metrics config
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent:
      endpoint: "jaeger:6831"
    service_name: "clair"
metrics:
  name: "prometheus"
